[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[edge_functions]]
  function = "og-param-proxy"
  path = "/game/*"

[build]
  publish = "myriad_yew/dist"
  command = "rustup update && cargo install trunk --force && trunk build myriad_yew/index.html --release"


[context.production]
environment = { NETLIFY_EXPERIMENTAL_BUILD_RUST_SOURCE = "true" }